from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.index,name='index'),
    path('adminpage',views.admin,name='adminpage'),
    path('login',views.login_action,name='login'),
    path('user_register',views.user_register,name='user_register'),
    path('admin_user_view',views.admin_user_view,name='admin_user_view'),
    path('user_home',views.user_home,name='user_home'),
    path('user_profile_edit',views.user_profile,name='user_profile_edit'),
    path('restaurant_registration',views.restaurant_registration, name='restaurant_registration'),
    path('staff_registration',views.staff_registration,name='staff_registration'),
    path('food_and_safety_registration',views.food_and_safety_department_registration, name='food_and_safety_registration'),
    path('admin_restaurant_view',views.admin_restaurant_view,name='admin_restaurant_view'),
    path('admin_staff_view',views.admin_staff_view,name='admin_staff_view'),
    path('restaurant_home',views.restaurant_home,name='restaurant_home'),
    path('staff_home',views.staff_home,name='staff_home'),
    path('department_home',views.department_home,name='department_home'),
    path('restaurant_profile',views.restaurant_profile,name="restaurant_profile"),
    path('staff_profile',views.staff_profile,name="staff_profile"),
    path('restaurant_cards',views.restaurant_cards,name='restaurant_cards'),
    path('staff_cards',views.staff_cards,name="staff_cards"),
    path('add_dish',views.add_dish,name="add_dish"),
    path('restaurant_dish_view',views.restaurant_dish_view,name='restaurant_dish_view'),
    path('logout_view',views.logout_view,name='logout_view'),
    path('user_restaurant_view/<int:id>',views.user_restaurant_view,name='user_restaurant_view'),
    path('staff_dish_view',views.staff_dish_view,name='staff_dish_view'),
    path('staff_dish_edit/<int:id>',views.staff_dish_edit,name='staff_dish_edit'),
    path('staff_dish_delete/<int:id>',views.dish_remove,name='staff_dish_delete'),
    path('staff_menu',views.staff_menu_view,name='staff_menu'),
    path('staff_add_menu/<int:id>',views.add_to_menu,name='staff_add_menu'),
    path('menu_item_remove/<int:id>',views.menu_item_remove,name='menu_item_remove'),
    path('add_to_cart/<int:restaurant_id>/<int:product_id>/',views.add_to_cart,name='add_to_cart'),
    path('user_cart_view',views.user_cart_view,name='user_cart_view'),
    path('cart_item_remove/<str:id>',views.cart_item_remove,name='cart_item_remove'),
    path('payment_form/<str:id>/',views.payment_forms,name='payment_form'),
    path('user_order_view',views.user_order_view,name='user_order_view'),
    path('restaurant_order_view',views.restaurant_order_view,name='restaurant_order_view'),
    path('user_restaurant_chat/<int:id>',views.user_restaurant_chat,name='user_restaurant_chat'),
    path('restaurant_chat_list_view',views.restaurant_chat_list_view,name='restaurant_chat_list_view'),
    path('restaurant_user_chat/<int:id>',views.restaurant_user_chat,name='restaurant_user_chat'),
    path('table_reservation/<int:id>',views.table_reservation,name='table_reservation'),
    path('restaurant_reservation_view',views.restaurant_reservation_view,name='restaurant_reservation_view'),
    path('staff_reservation_view',views.staff_reservation_view,name='staff_reservation_view'),
    path('user_reservation_view',views.user_reservation_view,name='user_reservation_view'),
    path('user_review/<int:id>',views.user_write_review,name='user_review'),
    path('view_ratings/<int:id>',views.view_ratings,name='view_ratings'),
    path('user_review_view',views.user_review_view,name='user_review_view'),
    path('user_edit_review/<int:id>',views.user_edit_review,name='user_edit_review'),
    path('user_delete_review/<int:id>',views.user_delete_review,name='user_delete_review'),
    path('user_cancel_order/<int:id>',views.user_cancel_order,name='user_cancel_order'),
    path('staff_order_view',views.staff_order_view,name='staff_order_view'),
    path('order_ready/<int:id>',views.order_ready,name='order_ready'),
    path('upi_payment/<str:id>/',views.upi_payment,name='upi_payment'),
    path('pay_at_pickup/<str:id>/',views.pay_at_pickup,name='pay_at_pickup'),
    path('admin_remove_user/<int:id>',views.admin_remove_user,name='admin_remove_user'),
    path('admin_remove_restuurant/<int:id>',views.admin_remove_restuurant,name='admin_remove_restuurant'),
    path('admin_remove_staff/<int:id>',views.admin_remove_staff,name='admin_remove_staff'),
    path('user_complaint',views.user_complaint,name='user_complaint'),
    path('admin_view_pending_restaurant',views.admin_view_pending_restaurant,name='admin_view_pending_restaurant'),
    path('admin_approve_restaurant/<int:id>',views.admin_approve_restaurant,name='admin_approve_restaurant'),
    path('admin_reject_restaurant/<int:id>',views.admin_reject_restaurant,name='admin_reject_restaurant'),
    path('admin_view_freezed_restaurants',views.admin_view_freezed_restaurants,name='admin_view_freezed_restaurants'),
    path('admin_freeze_restaurant/<int:id>',views.admin_freeze_restaurant,name='admin_freeze_restaurant'),
    path('user_report_restaurant/<int:id>',views.user_report_restaurant,name='user_report_restaurant'),
    path('admin_view_user_report',views.admin_view_user_report,name='admin_view_user_report'),
        path('update_cart_quantities/', views.update_cart_quantities, name='update_cart_quantities'),


]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
