# Generated by Django 5.1.4 on 2025-02-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0002_restaurants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=3)),
                ('contact', models.CharField(max_length=15)),
                ('restaurant_name', models.CharField(max_length=100)),
            ],
        ),
    ]
