# Generated by Django 5.1.4 on 2025-02-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0005_foodsafetydepartment_login_id_restaurants_login_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodsafetydepartment',
            name='login_id',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='login_id',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='login_id',
        ),
    ]
