# Generated by Django 5.1.4 on 2025-02-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0006_remove_foodsafetydepartment_login_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='login_id',
        ),
    ]
