# Generated by Django 5.1.4 on 2025-02-08 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0007_remove_users_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='login_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='RestaurantApp.login'),
            preserve_default=False,
        ),
    ]
