# Generated by Django 5.1.4 on 2025-02-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0009_foodsafetydepartment_login_id_restaurants_login_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='restaurant_name',
            field=models.IntegerField(),
        ),
    ]
