# Generated by Django 5.1.4 on 2025-02-10 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0016_alter_staffs_restaurant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('dish_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('price', models.CharField(max_length=10)),
                ('image', models.FileField(upload_to='dishes')),
                ('added_date', models.DateField(auto_now_add=True)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantApp.login')),
            ],
        ),
    ]
