# Generated by Django 5.1.4 on 2025-02-16 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0017_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='image',
            field=models.FileField(upload_to='dishes/'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='restaurant_name',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='RestaurantApp.restaurants'),
        ),
    ]
