# Generated by Django 5.1.4 on 2025-02-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0018_alter_dishes_image_alter_staffs_restaurant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
