# Generated by Django 5.1.4 on 2025-02-23 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0020_usercart'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='resturant_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='RestaurantApp.login'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='RestaurantApp.login'),
        ),
    ]
