# Generated by Django 5.1.4 on 2025-02-23 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0021_usercart_resturant_id_alter_usercart_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='resturant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='RestaurantApp.login'),
        ),
    ]
