# Generated by Django 5.1.4 on 2025-02-23 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0023_rename_resturant_id_usercart_resturant_loginid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercart',
            old_name='resturant_loginid',
            new_name='restaurant_loginid',
        ),
    ]
