# Generated by Django 5.1.4 on 2025-02-26 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0024_rename_resturant_loginid_usercart_restaurant_loginid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
                ('expiry_month', models.IntegerField(max_length=10)),
                ('expiry_year', models.IntegerField(max_length=10)),
                ('cvv_code', models.IntegerField()),
                ('owner_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantApp.usercart')),
            ],
        ),
    ]
