# Generated by Django 5.1.4 on 2025-02-26 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0026_alter_paymentdetails_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantApp.staffs'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='cvv_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='expiry_month',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='expiry_year',
            field=models.CharField(max_length=4),
        ),
    ]
