# Generated by Django 5.1.4 on 2025-03-03 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0027_alter_dishes_login_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='restaurant_loginid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='RestaurantApp.restaurants'),
        ),
    ]
