# Generated by Django 5.1.4 on 2025-03-03 09:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0028_alter_usercart_restaurant_loginid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='cartid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
