# Generated by Django 5.1.4 on 2025-03-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0029_usercart_cartid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='cartid',
            field=models.UUIDField(editable=False),
        ),
    ]
