# Generated by Django 5.1.4 on 2025-03-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0031_alter_paymentdetails_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='payment_status',
            field=models.IntegerField(default=0),
        ),
    ]
