# Generated by Django 5.1.4 on 2025-03-07 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0033_alter_users_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodsafetydepartment',
            name='department_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='login_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='RestaurantApp.login'),
        ),
    ]
