# Generated by Django 5.1.4 on 2025-03-08 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0034_alter_foodsafetydepartment_department_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.TextField()),
                ('current_date', models.DateField(auto_now_add=True)),
                ('current_time', models.TimeField(auto_now_add=True)),
                ('restaurant_reciever_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_reciever_id', to='RestaurantApp.restaurants')),
                ('restaurant_sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_sender_id', to='RestaurantApp.restaurants')),
                ('user_reciever_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reciever_id', to='RestaurantApp.users')),
                ('user_sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sender_id', to='RestaurantApp.users')),
            ],
        ),
    ]
