# Generated by Django 5.1.4 on 2025-03-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0035_chats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chats',
        ),
    ]
