# Generated by Django 5.1.4 on 2025-03-08 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0037_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='restaurant_reciever_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_reciever_id', to='RestaurantApp.restaurants'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='restaurant_sender_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_sender_id', to='RestaurantApp.restaurants'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user_reciever_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reciever_id', to='RestaurantApp.users'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user_sender_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sender_id', to='RestaurantApp.users'),
        ),
    ]
