# Generated by Django 5.1.4 on 2025-03-09 05:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0038_alter_chat_restaurant_reciever_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='current_date',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='current_time',
        ),
        migrations.AddField(
            model_name='chat',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
