# Generated by Django 5.1.4 on 2025-03-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0039_remove_chat_current_date_remove_chat_current_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='card_number',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='cart_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='cvv_code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='expiry_month',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='expiry_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='owner_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
