# Generated by Django 5.1.4 on 2025-03-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0040_alter_paymentdetails_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='card_number',
            field=models.IntegerField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='cvv_code',
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='expiry_month',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='expiry_year',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
