# Generated by Django 5.1.4 on 2025-03-16 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0041_alter_paymentdetails_card_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.IntegerField()),
                ('rdate', models.DateField()),
                ('rtime', models.TimeField()),
                ('notes', models.TextField()),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantApp.restaurants')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantApp.users')),
            ],
        ),
    ]
