# Generated by Django 5.1.4 on 2025-03-22 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0042_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(null=True, upload_to='image/')),
                ('review', models.TextField()),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantApp.restaurants')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantApp.users')),
            ],
        ),
    ]
