# Generated by Django 5.1.4 on 2025-03-22 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0043_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='current_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
