# Generated by Django 5.1.4 on 2025-03-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0044_reviews_current_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='order_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
