# Generated by Django 5.1.4 on 2025-03-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0045_usercart_order_status_usercart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='star',
            field=models.IntegerField(default=0),
        ),
    ]
