# Generated by Django 5.1.4 on 2025-03-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0046_reviews_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='images',
            field=models.FileField(upload_to='image/'),
        ),
    ]
