# Generated by Django 5.1.4 on 2025-03-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0047_alter_reviews_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='payment_method',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
