# Generated by Django 5.1.4 on 2025-03-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0048_usercart_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='upi',
            field=models.CharField(default=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='upi_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
