# Generated by Django 5.1.4 on 2025-04-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0052_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='approval_status',
            field=models.IntegerField(default=0),
        ),
    ]
