# Generated by Django 5.1.4 on 2025-04-06 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0056_alter_usercart_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='RestaurantApp.users'),
        ),
    ]
