# Generated by Django 5.1.4 on 2025-04-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0057_alter_usercart_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='remove_status',
            field=models.IntegerField(default=0),
        ),
    ]
