# Generated by Django 5.1.4 on 2025-04-19 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0058_usercart_remove_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercart',
            old_name='remove_status',
            new_name='cancel_status',
        ),
    ]
