# Generated by Django 5.1.4 on 2025-04-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0059_rename_remove_status_usercart_cancel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='remove_status',
            field=models.IntegerField(default=0),
        ),
    ]
