# Generated by Django 5.1.4 on 2025-04-29 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0060_usercart_remove_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='food_security_certificate',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='pollution_certificate',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
