# Generated by Django 5.1.4 on 2025-04-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0061_restaurants_food_security_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('current_date', models.DateField(auto_now_add=True)),
                ('current_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
