# Generated by Django 5.1.4 on 2025-04-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0063_announcements_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='food_security_certificate',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='pollution_certificate',
        ),
    ]
