# Generated by Django 5.1.4 on 2025-04-29 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0064_remove_restaurants_food_security_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('validity', models.IntegerField(default=1)),
                ('mobile', models.IntegerField()),
                ('tel', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('res_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantApp.restaurants')),
            ],
        ),
    ]
