# Generated by Django 5.1.4 on 2025-04-29 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0065_certificate_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate_application',
            name='current_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
