# Generated by Django 5.1.4 on 2025-04-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0066_certificate_application_current_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='fssai_nunmber',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='have_certificate',
            field=models.IntegerField(default=0),
        ),
    ]
