# Generated by Django 5.1.4 on 2025-04-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0067_restaurants_fssai_nunmber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='have_certificate',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=0),
        ),
    ]
