# Generated by Django 5.1.4 on 2025-04-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0068_alter_restaurants_have_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='have_certificate',
            field=models.IntegerField(default=0),
        ),
    ]
