# Generated by Django 5.1.4 on 2025-05-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0069_alter_restaurants_have_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate_application',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
