# Generated by Django 5.1.4 on 2025-05-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0070_certificate_application_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='department_approved',
            field=models.IntegerField(default=0),
        ),
    ]
