# Generated by Django 5.1.4 on 2025-05-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0071_restaurants_department_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate_application',
            name='owner_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
