# Generated by Django 5.1.4 on 2025-05-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0072_certificate_application_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreports',
            name='forward_to_dept',
            field=models.IntegerField(default=0),
        ),
    ]
