# Generated by Django 5.1.4 on 2025-05-05 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0073_userreports_forward_to_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_time_field', models.DateTimeField(auto_now_add=True)),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantApp.restaurants')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantApp.staffs')),
            ],
        ),
    ]
