# Generated by Django 5.1.4 on 2025-05-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0074_staffmessages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffmessages',
            old_name='date_time_field',
            new_name='data_and_time',
        ),
        migrations.RenameField(
            model_name='staffmessages',
            old_name='message',
            new_name='messages',
        ),
    ]
