# Generated by Django 5.1.4 on 2025-05-06 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0075_rename_date_time_field_staffmessages_data_and_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmessages',
            name='data_and_time',
        ),
        migrations.AddField(
            model_name='staffmessages',
            name='current_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffmessages',
            name='current_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
