# Generated by Django 5.1.4 on 2025-05-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0076_remove_staffmessages_data_and_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
