# Generated by Django 5.1.4 on 2025-05-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0078_restaurants_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
